[package]
name = "tokio-reqwest-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = "0.17.2"
reqwest = "0.12.4"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
